### ISSUE TITLE
跳转问题

### ISSUE THREAD

**Issue by dagu152** [yuzaimala/URL-detection-jump#1]
大佬你好 设置好以后不跳转 方便解答一下吗

**Comment by v2gou** [comment]
我也是 倒计时结束后没反应

**Comment by yuzaimala** [comment]
@634353267 @dagu152 
如果设置好后不跳转，请检查被检测网站是否允许跨域，如果没有允许跨域，会检测失败。

**Comment by dagu152** [comment]
https://api.yf50.cn

yuzaimala ***@***.***> 于 2024年8月18日周日 23:11写道：

**Comment by dagu152** [comment]
https://sun.755.cn  饿直接用这个

yuzaimala ***@***.***> 于 2024年9月19日周四 04:41写道：
